# Generated by Django 6.0.1 on 2026-01-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerapplication',
            name='availability',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='skills',
            field=models.TextField(blank=True),
        ),
    ]
