# Generated by Django 6.0.1 on 2026-01-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnershipinquiry',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
